provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  hello:
    lang: go
    handler: ./hello
    image: k33g/hello:latest
  hi:
    lang: node
    handler: ./hi
    image: k33g/hi:latest
  welcome:
    lang: node
    handler: ./welcome
    image: k33g/welcome:latest
